services:
  web:
    build: .  
    volumes:
      - .:/app
    command: python -m app.app
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgresql://user:password@db/pisadaprodb"
      FLASK_DEBUG: "1"
    depends_on:
      - db
      - product-service
      - rabbitmq

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pisadaprodb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongodb:
    image: mongo
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  product-service:
    build: ./product-service 
    volumes:
      - .:/product-service:/usr/src/app
    ports:
      - "3000:3000"  
    environment:
      MONGO_URL: "mongodb://mongodb:27017/productdb"
    depends_on:
      - mongodb
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672" 
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    networks:
      - pisadapro_network

networks:
  pisadapro_network:
    driver: bridge

volumes:
  postgres_data:
  mongo_data:
