version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pisadapro_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"

  nodejs:
    image: node:18
    working_dir: /app
    volumes:
      - ./backend:/app
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongodb

  python:
    image: python:3.11
    working_dir: /app
    volumes:
      - ./scripts:/app
    command: sh -c "pip install -r requirements.txt && python main.py"
    ports:
      - "5000:5000"
    depends_on:
      - postgres

  react:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm start"
    ports:
      - "3001:3001"

  redis:
    image: redis:7
    ports:
      - "6379:6379"
  
volumes:
  postgres_data:
  mongodb_data:
